/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequisitesRouteImport } from './routes/requisites'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PersonalDataRouteImport } from './routes/personal-data'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortfolioRde163RouteImport } from './routes/portfolio.rde163'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DemoPrintRouteImport } from './routes/demo.print'
import { Route as DemoChapterRouteImport } from './routes/demo.$chapter'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRefsRouteImport } from './routes/admin.refs'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminDiscountsRouteImport } from './routes/admin.discounts'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCrossesRouteImport } from './routes/admin.crosses'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CatalogBrandSlugRouteImport } from './routes/catalog.brand.$slug'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksSyncCatalogRouteImport } from './routes/api/public/hooks/sync-catalog'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitesRoute = RequisitesRouteImport.update({
  id: '/requisites',
  path: '/requisites',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataRoute = PersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortfolioRde163Route = PortfolioRde163RouteImport.update({
  id: '/portfolio/rde163',
  path: '/portfolio/rde163',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrintRoute = DemoPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => DemoRoute,
} as any)
const DemoChapterRoute = DemoChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => DemoRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefsRoute = AdminRefsRouteImport.update({
  id: '/refs',
  path: '/refs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrossesRoute = AdminCrossesRouteImport.update({
  id: '/crosses',
  path: '/crosses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogBrandSlugRoute = CatalogBrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => CatalogRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncCatalogRoute =
  ApiPublicHooksSyncCatalogRouteImport.update({
    id: '/api/public/hooks/sync-catalog',
    path: '/api/public/hooks/sync-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/contacts': typeof ContactsRoute
  '/demo': typeof DemoRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/requisites': typeof RequisitesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/crosses': typeof AdminCrossesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/refs': typeof AdminRefsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/$chapter': typeof DemoChapterRoute
  '/demo/print': typeof DemoPrintRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portfolio/rde163': typeof PortfolioRde163Route
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/catalog/brand/$slug': typeof CatalogBrandSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/sync-catalog': typeof ApiPublicHooksSyncCatalogRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/contacts': typeof ContactsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/requisites': typeof RequisitesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/crosses': typeof AdminCrossesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/refs': typeof AdminRefsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/$chapter': typeof DemoChapterRoute
  '/demo/print': typeof DemoPrintRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portfolio/rde163': typeof PortfolioRde163Route
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/demo': typeof DemoIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/catalog/brand/$slug': typeof CatalogBrandSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/sync-catalog': typeof ApiPublicHooksSyncCatalogRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/certificates': typeof CertificatesRoute
  '/contacts': typeof ContactsRoute
  '/demo': typeof DemoRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/requisites': typeof RequisitesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/crosses': typeof AdminCrossesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/refs': typeof AdminRefsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/$chapter': typeof DemoChapterRoute
  '/demo/print': typeof DemoPrintRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/portfolio/rde163': typeof PortfolioRde163Route
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/catalog/brand/$slug': typeof CatalogBrandSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/sync-catalog': typeof ApiPublicHooksSyncCatalogRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/certificates'
    | '/contacts'
    | '/demo'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/personal-data'
    | '/privacy-policy'
    | '/register'
    | '/requisites'
    | '/reset-password'
    | '/reviews'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/analytics'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/crosses'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/refs'
    | '/admin/reviews'
    | '/blog/$slug'
    | '/demo/$chapter'
    | '/demo/print'
    | '/email/unsubscribe'
    | '/portfolio/rde163'
    | '/admin/'
    | '/blog/'
    | '/demo/'
    | '/admin/orders/$id'
    | '/catalog/brand/$slug'
    | '/lovable/email/suppression'
    | '/api/public/hooks/sync-catalog'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/catalog'
    | '/certificates'
    | '/contacts'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/personal-data'
    | '/privacy-policy'
    | '/register'
    | '/requisites'
    | '/reset-password'
    | '/reviews'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/analytics'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/crosses'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/refs'
    | '/admin/reviews'
    | '/blog/$slug'
    | '/demo/$chapter'
    | '/demo/print'
    | '/email/unsubscribe'
    | '/portfolio/rde163'
    | '/admin'
    | '/blog'
    | '/demo'
    | '/admin/orders/$id'
    | '/catalog/brand/$slug'
    | '/lovable/email/suppression'
    | '/api/public/hooks/sync-catalog'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/certificates'
    | '/contacts'
    | '/demo'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/personal-data'
    | '/privacy-policy'
    | '/register'
    | '/requisites'
    | '/reset-password'
    | '/reviews'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/admin/analytics'
    | '/admin/catalog'
    | '/admin/content'
    | '/admin/crosses'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/refs'
    | '/admin/reviews'
    | '/blog/$slug'
    | '/demo/$chapter'
    | '/demo/print'
    | '/email/unsubscribe'
    | '/portfolio/rde163'
    | '/admin/'
    | '/blog/'
    | '/demo/'
    | '/admin/orders/$id'
    | '/catalog/brand/$slug'
    | '/lovable/email/suppression'
    | '/api/public/hooks/sync-catalog'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  CertificatesRoute: typeof CertificatesRoute
  ContactsRoute: typeof ContactsRoute
  DemoRoute: typeof DemoRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PersonalDataRoute: typeof PersonalDataRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  RequisitesRoute: typeof RequisitesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PortfolioRde163Route: typeof PortfolioRde163Route
  BlogIndexRoute: typeof BlogIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksSyncCatalogRoute: typeof ApiPublicHooksSyncCatalogRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisites': {
      id: '/requisites'
      path: '/requisites'
      fullPath: '/requisites'
      preLoaderRoute: typeof RequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data': {
      id: '/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof PersonalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portfolio/rde163': {
      id: '/portfolio/rde163'
      path: '/portfolio/rde163'
      fullPath: '/portfolio/rde163'
      preLoaderRoute: typeof PortfolioRde163RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/print': {
      id: '/demo/print'
      path: '/print'
      fullPath: '/demo/print'
      preLoaderRoute: typeof DemoPrintRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/$chapter': {
      id: '/demo/$chapter'
      path: '/$chapter'
      fullPath: '/demo/$chapter'
      preLoaderRoute: typeof DemoChapterRouteImport
      parentRoute: typeof DemoRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refs': {
      id: '/admin/refs'
      path: '/refs'
      fullPath: '/admin/refs'
      preLoaderRoute: typeof AdminRefsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crosses': {
      id: '/admin/crosses'
      path: '/crosses'
      fullPath: '/admin/crosses'
      preLoaderRoute: typeof AdminCrossesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/brand/$slug': {
      id: '/catalog/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/catalog/brand/$slug'
      preLoaderRoute: typeof CatalogBrandSlugRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-catalog': {
      id: '/api/public/hooks/sync-catalog'
      path: '/api/public/hooks/sync-catalog'
      fullPath: '/api/public/hooks/sync-catalog'
      preLoaderRoute: typeof ApiPublicHooksSyncCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCrossesRoute: typeof AdminCrossesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminRefsRoute: typeof AdminRefsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCrossesRoute: AdminCrossesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminRefsRoute: AdminRefsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CatalogRouteChildren {
  CatalogBrandSlugRoute: typeof CatalogBrandSlugRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogBrandSlugRoute: CatalogBrandSlugRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface DemoRouteChildren {
  DemoChapterRoute: typeof DemoChapterRoute
  DemoPrintRoute: typeof DemoPrintRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoChapterRoute: DemoChapterRoute,
  DemoPrintRoute: DemoPrintRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRouteWithChildren,
  CertificatesRoute: CertificatesRoute,
  ContactsRoute: ContactsRoute,
  DemoRoute: DemoRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PersonalDataRoute: PersonalDataRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  RequisitesRoute: RequisitesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PortfolioRde163Route: PortfolioRde163Route,
  BlogIndexRoute: BlogIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksSyncCatalogRoute: ApiPublicHooksSyncCatalogRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
